setlocal showmatch
setlocal tabstop=4
setlocal softtabstop=4
setlocal shiftwidth=4
setlocal textwidth=80
setlocal autoindent  
setlocal smartindent  
setlocal smarttab
setlocal expandtab
setlocal number
